### ISSUE TITLE
Investigate how to support multiple design codes

### ISSUE THREAD

**Issue by mapra99** [PradaIng/structuraid-core#13]
https://www.notion.so/Patrones-de-dise-o-23232cd915784e13b621534f97ef6c7b

**Comment by mapra99** [comment]
https://refactoring.guru/es/design-patterns/adapter
https://refactoring.guru/es/design-patterns/mediator

**Comment by ImMPrada** [comment]
https://www.notion.so/Patrones-de-dise-o-23232cd915784e13b621534f97ef6c7b

**Comment by mapra99** [comment]
We're picking the mediator pattern. Thanks @ImMPrada !
